CLASS zcl_amdp_aug_26 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_amdp_marker_hdb .

    CLASS-METHODS : calculate_age FOR SCALAR FUNCTION ZSCALAR_FUN_CALCULATE_AGE.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_amdp_aug_26 IMPLEMENTATION.
  METHOD calculate_age BY DATABASE FUNCTION FOR HDB LANGUAGE SQLSCRIPT OPTIONS READ-ONLY.
    result = dats_days_between( birthdate, '20260917' ) / 365 ;
  ENDMETHOD.

ENDCLASS.
